### ISSUE TITLE
Error: Could not find or load main class main.Main

### ISSUE THREAD

**Issue by ssl** [sirjonasxx/G-Earth#10]
Error:
```
iMac:g-earth elyesa$ sudo -E java -jar G-Earth.jar
Error: Could not find or load main class main.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

on: macOS Sierra 10.12.6

**Comment by sirjonasxx** [comment]
are you using java 8?

**Comment by sirjonasxx** [comment]
ps; current releases do not support macOS yet, but you should be able to launch it

**Comment by ssl** [comment]
> JavaFX isn't bundled with Java 11 so I'd recommend installing JDK 1.8

Thanks, that fixed it.

> ps; current releases do not support macOS yet, but you should be able to launch it

Ah, sucks. So can't packetlog on mac at all?

**Comment by XePeleato** [comment]
@ssl I was able to (when I updated to Mojave it stopped working), compiling the macDev branch, however macOs implements some new (or not so new) kind of security that doesn't allow G-Mem to get the task port of the flash player process, (same error as in here https://stackoverflow.com/questions/13913818/how-to-get-a-codesigned-gdb-on-osx ) so if you build it from source and fix that signing issue it _should_ work.
