### ISSUE TITLE
G-Earth on macbook m1 ?

### ISSUE THREAD

**Issue by TheRevenge** [sirjonasxx/G-Earth#132]
Hi !
I've been trying to run G-Earth on my macbook m1, and I get the classical following error : 

> Error: Could not find or load main class gearth.GEarth
> Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

So I installed JDK 1.8 from [here](https://adoptium.net/temurin/releases/?version=8), sadly even after a reboot, I still get that error.
That's when I noticed that the OG JDK 1.8 doesn't support ARM architecture... which is quite a problem here.

Does anyone have an idea to solve this ?
Btw, here's the output of _java --version_:

> openjdk 17.0.2 2022-01-18 LTS
> OpenJDK Runtime Environment (build 17.0.2+9-LTS)
> OpenJDK 64-Bit Server VM (build 17.0.2+9-LTS, mixed mode, sharing)

Thanks in advance !

**Comment by XePeleato** [comment]
What about using another JDK flavour? I personally like Azul's JDK https://www.azul.com/downloads/?os=macos&architecture=arm-64-bit&package=jdk give it a try!

PS: Remember to download Java 8

**Comment by TheRevenge** [comment]
> What about using another JDK flavour? I personally like Azul's JDK https://www.azul.com/downloads/?os=macos&architecture=arm-64-bit&package=jdk give it a try!
> 
> PS: Remember to download Java 8

Well, thanks for the link ! I found an ARM flavour of the 1.8 JDK, installed it.
Of courses, I had to get rid of the others versions I already had in /Library/Java/JavaVirtualMachines/, now G-Earth launches ! Hurray !
