### ISSUE TITLE
Habbo stop charging in 76%

### ISSUE THREAD

**Issue by yale03** [sirjonasxx/G-Earth#16]
Hi, I'm trying to use G-Earth with windows in Habbo.com.br and I connect but the habbo to load in 76% can say how to solve this problem?

**Comment by XePeleato** [comment]
Can you try to run G-Earth.jar from an admin command prompt (java -jar G-Earth.jar)? Then whenever it gets stuck, check the command prompt for an error message, if there's any please post it here so that we can have a look.

**Comment by yale03** [comment]
![ddd](https://user-images.githubusercontent.com/4648977/51265544-28b62c00-19a0-11e9-8853-5d5c74058ea4.png)
I've seen here that my windows is not compatible, I think it's because it's 32bits, does it have some version that can be made available for 32bits? Or a way to work on this platform?

**Comment by sirjonasxx** [comment]
Hi, could you try and replace G-WinMem.exe in the G-Earth folder with the G-WinMem packaged in the zip file below? Please let us know if it works
[G-WinMem.zip](https://github.com/sirjonasxx/G-Earth/files/2765365/G-WinMem.zip)

**Comment by yale03** [comment]
Thank you, it worked perfectly!
