### ISSUE TITLE
Does not recognize habbo

### ISSUE THREAD

**Issue by gells66** [sirjonasxx/G-Earth#17]
On my computer he does not recognize the habbo, he just keeps waiting for a connection and the habbo charging and enters while he is waiting for a connection

**Comment by sirjonasxx** [comment]
Hi, could you check if this is your problem: https://github.com/sirjonasxx/G-Earth/issues/16

Otherwise, could you open cmd as administrator, navigate to the G-Earth folder and execute "java -jar G-Earth.jar", and show us the error message if there is any?

**Comment by gells66** [comment]
My windows is 64 bits, the program opens normal but does not detect habbo, I'll do what you said in cmd

**Comment by sirjonasxx** [comment]
can you enter just "java -jar G-Earth.jar" without "start" and did you try clicking connect & loading Habbo when taking this screenshot?

**Comment by gells66** [comment]
Yes I tried, so habbo loads and g-earth is just waiting for connection
![image](https://user-images.githubusercontent.com/46762812/51281090-90806d00-19c8-11e9-8147-3f0383d6c84d.png)

**Comment by sirjonasxx** [comment]
You should make sure that Administrators have full control over the Windows hosts file.
The image below might help you with this.

![image](https://user-images.githubusercontent.com/36828922/51281347-689e0300-19e2-11e9-9214-65bd7831bcbd.png)


Does the problem still occur after having tried this?

**Comment by gells66** [comment]
Leave the output as it continues with the same problem :(

![image](https://user-images.githubusercontent.com/46762812/51326529-7db47980-1a56-11e9-87f5-f0b1a89d23fc.png)

**Comment by sirjonasxx** [comment]
The screen you showed refers to the "hosts.ics" file and ot the hosts file (so without any file extension). Please create the hosts file if it's not in there

**Comment by gells66** [comment]
I went to the other hosting file and gave the user permission
![image](https://user-images.githubusercontent.com/46762812/51328437-860eb380-1a5a-11e9-9fcd-17385591718f.png)
![image](https://user-images.githubusercontent.com/46762812/51328492-a474af00-1a5a-11e9-9a8d-c3dc35f4c08b.png)

Do you have discord or teamviewer, so it would be easier

**Comment by sirjonasxx** [comment]
You can add me on discord: snirjeunsxx#7707

**Comment by gells66** [comment]
I sent you a request so it's easier to talk

**Comment by sirjonasxx** [comment]
He solved it by removing the old hosts file and replacing it by a new one

**Comment by Hanezx** [comment]
Sirjonasxx i changed my hosts file and it did not work

**Comment by Hanezx** [comment]
I have mi Java 8, i opened the G-Search with cmd and it opened without errors

**Comment by Hanezx** [comment]
But it did not recognize habbo

**Comment by miguegame621-design** [comment]
Hello, I put a new, empty host file and this is what I get: Waiting for connection but it doesn't connect. Please help.
