### ISSUE TITLE
No me conecta habbo en ningun otro navegador mas que chrome.

### ISSUE THREAD

**Issue by Unytiw7** [sirjonasxx/G-Earth#18]
[ReleaseVersion]
Outgoing[4000] -> [0][0][0]4[15] [0]!PRODUCTION-201901141210-114421986[0][5]FLASH[0][0][0][1][0][0][0][0]
{l}{u:4000}{s:PRODUCTION-201901141210-114421986}{s:FLASH}{i:1}{i:0}
--------------------
[InitCrypto]
Outgoing[44] -> [0][0][0][2][0],
{l}{u:44}
--------------------
[VerifyPrimes]
Incoming[1482] <- [0][0][4][6][5]Ê[2][0]885668260b54f705b38f05819bb8b92232d6fd29cf3f8a1291659a531561de0948337bb5dba5fbf647e98291b7e1ac960567783d1bd3f69aeffb9996668dd2462b0821adecb1999ce8e2debb516de0a0e22f556e02a9caba3b0551d0bcf0e7874a5dfbb226cf14ecba9f5054249e1f191abbd80707dd11486a419cf78f7f69db10eebe46f675b67ba4f05040d35b7aeb17c4e42a89bc979187623d95bd0f15f0775d8d754fea3974507213f798944bf91e01fb5705c20bdb12157406d37f66e4e6b68a43f77045b5dd816cbf50e748f3d99966ddb8277d677215b0730426db57c7dd2ec089b111e0584661f102745c5dc2fa77541c46b308bfa51e6b393ebcab[2][0]13a43066f11de2de7f457d2de97c005b303d86edd1ea2ffeb843db02d0e0c4838385ea89e8b72b2eea4c56ebb592e8d2ce6f4407764c0ea365bc97ac09f17dbf971f5f6d7202b206c8154dd7499ba0b8d25729c74f9f98b1d94f8bddd7ca891c9529d9723679b6dc0f397c46fb1ab0e5ab3d311834181789bdb48e3a78d5489dbf2e12b09ace06abe5ee51d00b9991d530ce026a344ad9e5a673fb55180ef5f11b9aadecdac463efe2c9fbb84d550364ced8e63f91eaea77e2933b9afbf7e1f8c293930a0ee1aaf89fcb5d870b17a85658722b66b2d1a907fc242e460deca2ed6325dca0c511278f9461f0dcc74e680439ca8c862cbf35be69713999944b3b0a
{l}{u:1482}{s:885668260b54f705b38f05819bb8b92232d6fd29cf3f8a1291659a531561de0948337bb5dba5fbf647e98291b7e1ac960567783d1bd3f69aeffb9996668dd2462b0821adecb1999ce8e2debb516de0a0e22f556e02a9caba3b0551d0bcf0e7874a5dfbb226cf14ecba9f5054249e1f191abbd80707dd11486a419cf78f7f69db10eebe46f675b67ba4f05040d35b7aeb17c4e42a89bc979187623d95bd0f15f0775d8d754fea3974507213f798944bf91e01fb5705c20bdb12157406d37f66e4e6b68a43f77045b5dd816cbf50e748f3d99966ddb8277d677215b0730426db57c7dd2ec089b111e0584661f102745c5dc2fa77541c46b308bfa51e6b393ebcab}{s:13a43066f11de2de7f457d2de97c005b303d86edd1ea2ffeb843db02d0e0c4838385ea89e8b72b2eea4c56ebb592e8d2ce6f4407764c0ea365bc97ac09f17dbf971f5f6d7202b206c8154dd7499ba0b8d25729c74f9f98b1d94f8bddd7ca891c9529d9723679b6dc0f397c46fb1ab0e5ab3d311834181789bdb48e3a78d5489dbf2e12b09ace06abe5ee51d00b9991d530ce026a344ad9e5a673fb55180ef5f11b9aadecdac463efe2c9fbb84d550364ced8e63f91eaea77e2933b9afbf7e1f8c293930a0ee1aaf89fcb5d870b17a85658722b66b2d1a907fc242e460deca2ed6325dca0c511278f9461f0dcc74e680439ca8c862cbf35be69713999944b3b0a}
--------------------
[GenerateSecretKey]
Outgoing[3802] -> [0][0][2][4][14]Ú[2][0]86d2f44c39da53441758e300027c6f110bc64d0612a515e28eeddccfca5e56e728a453232c5ef90ca864e339c0ef556621e583ee39098c466358b610bc15c549c4546dfc43764e946b729162ff4aec128e4e54912959220d070aaace8763e890ca0738e642302479354b7080c2efec971b809bb509594cc1692e5698342ec7a4137c628b24b1eac9b13d0b2b60839048b7dc2f4b9e291d5062c90facfe5636c616212da6d3c8f66eba4bae1bb94f12719c2cecc0195b5978235d29f5509e42b1e3db63b2470f90be8e8403ac06fd88d5844a6f2b5d0116c2b7738f68cbf4b04fb512f8115de57ffc36b9ab5f1f5f37cd2c04fdf9878acddb5316631152b3eb16
{l}{u:3802}{s:86d2f44c39da53441758e300027c6f110bc64d0612a515e28eeddccfca5e56e728a453232c5ef90ca864e339c0ef556621e583ee39098c466358b610bc15c549c4546dfc43764e946b729162ff4aec128e4e54912959220d070aaace8763e890ca0738e642302479354b7080c2efec971b809bb509594cc1692e5698342ec7a4137c628b24b1eac9b13d0b2b60839048b7dc2f4b9e291d5062c90facfe5636c616212da6d3c8f66eba4bae1bb94f12719c2cecc0195b5978235d29f5509e42b1e3db63b2470f90be8e8403ac06fd88d5844a6f2b5d0116c2b7738f68cbf4b04fb512f8115de57ffc36b9ab5f1f5f37cd2c04fdf9878acddb5316631152b3eb16}
--------------------
[GenerateSecretKey]
Incoming[2369] <- [0][0][2][5][9]A[2][0]4d600e9843e81410dfbbad6d03a91bae0ac79645e9c877e1836fff2647c1fe1073b186fdf9f7d0771aaec192cffb3d57e4e232201fcec837e34b9a9f024b1097f286434b43f30240fefda3123102dafbfe73e11424c2060403fa5534e6773cdb2518a19a703d861d0ccca80cd08c4e2c03ba410d64bcfc30f0248410bb425a4a16d5e985e608fa050556c31fd6abe7327643ee71f014788082228d14121012df39e0c77c1a914db68d88bd4e876a506f7c2c4c0243a7e61bc0f77dd0efe5c9616783ea7aa0d1fc290d6a9460acf425533b389ddf6946081bf879d53f5836ee20bf0ed7ab0147f4639b04b4dbdbbe33131d50ec24a27a1f8cabec1a4f2fea3e49[0]
{l}{u:2369}{s:4d600e9843e81410dfbbad6d03a91bae0ac79645e9c877e1836fff2647c1fe1073b186fdf9f7d0771aaec192cffb3d57e4e232201fcec837e34b9a9f024b1097f286434b43f30240fefda3123102dafbfe73e11424c2060403fa5534e6773cdb2518a19a703d861d0ccca80cd08c4e2c03ba410d64bcfc30f0248410bb425a4a16d5e985e608fa050556c31fd6abe7327643ee71f014788082228d14121012df39e0c77c1a914db68d88bd4e876a506f7c2c4c0243a7e61bc0f77dd0efe5c9616783ea7aa0d1fc290d6a9460acf425533b389ddf6946081bf879d53f5836ee20bf0ed7ab0147f4639b04b4dbdbbe33131d50ec24a27a1f8cabec1a4f2fea3e49}{b:false}
--------------------
[Ping]
Incoming[3385] <- [0][0][0][2][13]9
{l}{u:3385}
--------------------
[ErrorLogin]
Incoming[4000] <- [0][0][0][6][15] [0][0][0]q
{l}{u:4000}{i:113}
--------------------

**Comment by Unytiw7** [comment]
Eso es lo q me sale
en el packet porfavor pido ayuda.

**Comment by Unytiw7** [comment]
Explicare mas a fondo el problema , yo entro a habbo y se me queda en 76 y me conecta el packetlogger y todo pero el problema a fondo es que me sale
[Ping]
Incoming[3385] <- [0][0][0][2][13]9
{l}{u:3385}
[ErrorLogin]
Incoming[4000] <- [0][0][0][6][15] [0][0][0]q
{l}{u:4000}{i:113}

Y despues de esto no logra conectar y se queda pegado.

**Comment by XePeleato** [comment]
¿Con qué otros navegadores has probado? Firefox debería funcionar al igual que Chrome.

**Comment by Unytiw7** [comment]
Si el tema es que va muy lento por su webkit ocupan demaciada ram.

**Comment by Unytiw7** [comment]
Queria ver si hay alguna solucion a esos navegadores , espero respuesta porfavor.

**Comment by XePeleato** [comment]
Hola, acabo de probar en Maxthon y ha funcionado sin problemas.
![](https://i.imgur.com/Zdj9NUF.png)

Podrías probar a abrir una consola de comandos con permisos de administrador, ir a la carpeta de G-Earth y escribir "java -jar G-Earth.jar"? Cuando tengas ese problema, vuelve a la consola y comprueba si hay algún error.

**Comment by Unytiw7** [comment]
Jaja es que es maxthon 3 bro. los webkit antiguos no los toma.

**Comment by Unytiw7** [comment]
Te puedo contactar en habbo para q me expliques mejor porfavor¡

**Comment by Unytiw7** [comment]
No tengo idea que es abrir una consola de comandos con permisos de admin y lo q me explicas

**Comment by XePeleato** [comment]
Si el problema es sólo del navegador no hace falta que hagas eso. No he encontrado Maxthon 3, pero tampoco entiendo el motivo de usar una versión tan antigua, en la última funciona bien, y el rendimiento asumo que será mejor

**Comment by Unytiw7** [comment]
El rendimiento me va fatal y la version antigua consume menos memoria q la 5.

**Comment by Unytiw7** [comment]
http://m.majorgeeks.com/files/details/maxthon_3.html el link para el maxthon 3

**Comment by radyndon** [comment]
![image](https://user-images.githubusercontent.com/46834316/51422123-68436a80-1b90-11e9-8385-d84ea8c71093.png)
tengo el mismo problema, incluso con maxthon, persiste.

**Comment by Unytiw7** [comment]
Antes no pasaba esto.
y bueno el rendimiento va horrible sin esos navegadores
