### ISSUE TITLE
Error: Could not find or load main class gearth.Main

### ISSUE THREAD

**Issue by jordantbdm** [sirjonasxx/G-Earth#19]
Error whilst executing G-Earth.jar (Could not find or load main class gearth.Main)
I tried compiling from the source code directly, made sure the main class was correct in manifest.mf and still didn't work. I believe it might be something to do with my Java version.

Linux Distro: Elementary OS 0.4.1 Loki (Ubuntu based distribution)
Java Version: Open JDK 1.8.0_191

![issue g-earth](https://user-images.githubusercontent.com/29107939/51306680-dcb5c680-1a35-11e9-8c59-f43866aa3401.png)

**Comment by XePeleato** [comment]
Could you unpack the jar file and check if the main class is really inside? Your java version seems ok.

**Comment by jordantbdm** [comment]
The Main class is there, it has gearth as the package. I have a feeling it could be to do with the java command looking in the wrong place. Possibly change the Main class in Manifest.mf to
Main class: gearth/Main (rather than gearth.Main)

Unfortunately I won't be able to try it until I'm home in few days. If you have any suggestions or commands I could try for when I return, Let me know. I want to get this working on my OS so much :D

**Comment by sirjonasxx** [comment]
Can you try and execute "apt install openjfx"? This worked for Scott

**Comment by gabrielpacheco23** [comment]
Same issue here.
