### ISSUE TITLE
Error when trying to start the application

### ISSUE THREAD

**Issue by Paralusion** [sirjonasxx/G-Earth#2]
Error: Could not find or load main class main.Main
 when writing 'sudo -E java -jar G-Earth.jar'
in terminal.

**Comment by sirjonasxx** [comment]
Harble user tonmAr had the same issue and found a workaround:

> I had the same issue but managed to get around it by installing tons of random java packages. Later uninstalled some to find out which one actually solved the issue. Found out that I had to install oracle-java8-installer via ppa:webupd8team/java to not get that error anymore. After installing that, G-Earth could even be executed without openjdk-11-jdk and openjdk-11-jre

**Comment by sirjonasxx** [comment]
If your issue wasn't solved, consider co-operating without leaving a gap of 3 months inbetween. Do you still have the issue?
