### ISSUE TITLE
Extension Port

### ISSUE THREAD

**Issue by Pandafuchs** [sirjonasxx/G-Earth#25]
What does the "Port" under Extensions do? Is there a method to connect to the Extensions via TCP?

**Comment by sirjonasxx** [comment]
Hi,

Yes, extensions do connect to G-Earth via TCP. They also do not need to be installed for that reason. Packets get exchanged with the same protocol that Habbo uses.

The documentation on this you can find here: https://github.com/sirjonasxx/G-Earth/blob/master/G-Earth/src/main/java/gearth/ui/extensions/Extensions.java but might be slighly outdated. 

An extensipn-side implementation is right here https://github.com/sirjonasxx/G-Earth/blob/master/G-Earth/src/main/java/gearth/extensions/Extension.java
