### ISSUE TITLE
Helper Classes

### ISSUE THREAD

**Issue by Pandafuchs** [sirjonasxx/G-Earth#26]
There are a lot of Helper Classes in Geode:
https://github.com/ArachisH/Geode/tree/master/Geode/Habbo
Those are helpful if you want to iterate through all Habbos in the Room etc.

Are you gonna implement those into G-Earth anytime soon? If no I'll port them to Java and I could push them to git.

**Comment by XePeleato** [comment]
What about these: https://github.com/sirjonasxx/G-Earth/tree/master/G-Earth/src/main/java/gearth/extensions/parsers

**Comment by Pandafuchs** [comment]
Oh I didn't see those! Maybe that could be added to the documentation somewhere... :D
