### ISSUE TITLE
Does not recognize habbo

### ISSUE THREAD

**Issue by MrGladiatorian** [sirjonasxx/G-Earth#29]
Hello. My G-Earth is not connecting to my Habbo despite the fact Habbo itself is loading and I get normally in there. I have Windows 10 and my Java version is 8.0.2010.9.
![image](https://user-images.githubusercontent.com/47282095/52169024-91402f80-273a-11e9-8ddf-f02479d083f8.png)

**Comment by sirjonasxx** [comment]
solved with tommAr's suggestion to disable the virusscanner
