### ISSUE TITLE
G-Earth impractical name

### ISSUE THREAD

**Issue by sirjonasxx** [sirjonasxx/G-Earth#3]
Due to the existence of Google Earth, it's too hard to find G-Earth's github page or another download page through search engines.

I'm looking for a new project name, suggestions welcome

**Comment by ArachisH** [comment]
ICantGetToGrandChamp-Earth

**Comment by sirjonasxx** [comment]
IShouldBeGrantShamp-Earth

**Comment by ArachisH** [comment]
G-irth

**Comment by DevLooney** [comment]
Zanji
