### ISSUE TITLE
Dont connect the hotel

### ISSUE THREAD

**Issue by hidla** [sirjonasxx/G-Earth#30]
I open g-earth and connect the hotel . hotel is open but it still "waiting for connection" so dont connect the hotel 
I dont use vpn
I changing my host a new but still dont connect. I try java -jar G-earth.jar but
cmd say Error: Unable to acces jarfile G-earth.jar

I read all topics but not help Please help me :(

**Comment by XePeleato** [comment]
Please give us more information, is it an official hotel?

**Comment by hidla** [comment]
yeah habbo.com.tr

**Comment by XePeleato** [comment]
Which OS and browser have you tried this on?

**Comment by hidla** [comment]
windows 7 x64 google chrome and opera but same error in both browser

**Comment by hidla** [comment]
could find the problem

**Comment by hidla** [comment]
yeah, what is the problem could you find it ?

**Comment by hidla** [comment]
problem still contunies pls help

**Comment by XePeleato** [comment]
Windows says 
> Error: Unable to acces jarfile G-earth.jar

it can't find the file. What can we do about it? Nothing. What can you do about it? Maybe type carefully.

Most likely there's a typo here:
> java -jar G-**e**arth.jar

should be 
> java -jar G-**E**arth.jar
