### ISSUE TITLE
[ERROR]COULD NOT FIND RC4 TABLE

### ISSUE THREAD

**Issue by Armanta** [sirjonasxx/G-Earth#31]
![image](https://user-images.githubusercontent.com/35372027/52519240-8e709d80-2c58-11e9-9530-23c8615a179d.png)

**Comment by Armanta** [comment]
Also Habbo retro stuck on 76% , i download the c++ redistributable 2017 but nothing.



I also got an other problem, Why g-earth don't detect some Habbo retro (french copy )

**Comment by Armanta** [comment]
My discord: Blowfish#6201

**Comment by salfrancoo** [comment]
Hello! did you solve this problem? I have the same issue, can you please tell me how you fixed this? I'll appreciate that. my doscord: Sal Franco#9077
