### ISSUE TITLE
My habbo loads and the g-land does not, no program gets the message "waiting for connection"

### ISSUE THREAD

**Issue by DJSmoll** [sirjonasxx/G-Earth#33]
JAVA version 8
Windows 10 64 bits
http://prntscr.com/mv8j51

**Comment by XePeleato** [comment]
Run it as administrator, it clearly says that it lacks permissions.

**Comment by sirjonasxx** [comment]
I see you are running as administrator already, this might be an issue with the permissions of your HOSTS file. Try to replace it with a new one, there are some tutorials on this online

**Comment by DJSmoll** [comment]
But, couldn't you help me? I don't know how to replace the HOSTS file.

**Comment by sirjonasxx** [comment]
https://support.microsoft.com/en-us/help/972034/how-to-reset-the-hosts-file-back-to-the-default follow this tutorial from microsoft

**Comment by DJSmoll** [comment]
Do you still create g-earth extensions?

**Comment by sirjonasxx** [comment]
I don't, sorry
