### ISSUE TITLE
Issue trying to create my own module

### ISSUE THREAD

**Issue by sep1** [sirjonasxx/G-Earth#34]
Hello, i'm trying to create my own module using eclipse java. when i try to do "run as-> maven install" to create the jar file of the module i get this error:

Failed to execute goal on project HappySpeech: Could not resolve dependencies for project G-EarthGang:HappySpeech:jar:0.0.1-beta: Failure to find G-Earth:G-Earth:jar:1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by XePeleato** [comment]
Remove the extensions from G-Earth's pom.xml and then run maven install, then add them back. That should get G-Earth into maven's cache and allow you to compile your extensions.

**Comment by sep1** [comment]
What to you mean with "remove the extendions from G-Earth's pom.xml? Sorry, i'm not that good at programming.

**Comment by XePeleato** [comment]
From https://github.com/sirjonasxx/G-Earth/blob/master/pom.xml#L24 remove the three <module> tags and after installing it into maven's cache add them back

**Comment by sep1** [comment]
I think i'm doing something wrong importing the project. This is the structure:
https://imgur.com/X0mOU1q
Is it correct?

**Comment by XePeleato** [comment]
Looks good to me, just delete the modules (extensions) from the G-Earth pom. I use IntelliJ but eclipse should work as well

**Comment by sep1** [comment]
Ok, solved. Thanks! I'll open another ticket for another issue.
