### ISSUE TITLE
Username for [RoomUserTalk] package and User list for [UsersRoom] package

### ISSUE THREAD

**Issue by sep1** [sirjonasxx/G-Earth#36]
Assuming i want to know the user id and the username for a "RoomUserTalk" package:
`{l}{u:830}{i:6313}{s:whatever}{i:0}{i:0}{i:0}{i:-1}`
the integer in the first position it's not the user id and i can't retrieve the username nor the user id.

Different thing is for the "RoomUsers" package. I have this big packet, how can i read users one by one? HUserProfile.java should be the solution but it's just for one user and not for the user list.
`{l}{u:1731}{i:6}{i:9897539}{s:Luposolitario87}{s:Sono solo il riflesso del tuo alterego}{s:hr-170-42.hd-180-10.ch-235-1408.lg-3290-64.sh-305-73.ea-1406.fa-1206-64.ca-1804-64.wa-2009-1408.cc-3389-73-1408}{i:0}{i:1}{i:14}{s:0.0}{i:2}{i:1}{i:93440}{b:true}{b:69}{b:47}{i:3}{s:Regalo}{i:0}{i:123338752}{b:149}{b:128}{b:190}{s:Teeteto}{s:}{s:hr-555-37.hd-615-10.ch-660-1408.lg-710-82.sh-735-64.ha-1006}{i:16}{i:1}{i:12}{s:0.0}{i:2}{i:1}{s:f}{i:-1}{i:-1}{i:0}{i:1004}{i:38677}{b:252}{s:LupoVenexian}{s:Ufficiale in prova M.M.H}{s:hr-802-42.hd-180-1.ch-235-72.lg-3023-64.sh-305-73.fa-1206-64.ca-3423-66-66.wa-2007}{i:2}{i:1}{i:15}{s:0.0}{i:2}{i:1}{i:93440}{b:true}{b:66}{b:129}{i:3}{s:Marina Militare Habbo}{i:0}{i:80216064}{b:151}{b:17}{b:168}{s:Karterino}{s:}{s:hr-893-45.hd-205-10.ch-255-1408.lg-285-82.sh-295-1408.ha-1006}{i:19}{i:1}{i:13}{s:0.0}{i:2}{i:1}{i:93440}{b:true}{b:69}{b:240}{i:3}{s:seduta con shikon}{i:0}{i:72679424}{b:146}{b:86}{b:102}{s:manuel3990}{s: Marinaio M.M.H.}{s:hr-3090-36.hd-209-1370.ch-220-81.lg-270-64.sh-3068-82-82.ha-1023-81.ea-1403-64.ca-1804-82.wa-2009-64}{i:21}{i:1}{i:16}{s:0.0}{i:2}{i:1}{i:93440}{b:true}{b:66}{b:129}{i:3}{s:Marina Militare Habbo}{i:0}{i:263389184}{b:151}{b:37}{b:24}{s:2x2x2}{s:}{s:hr-115-31.hd-209-10.ch-255-74.lg-280-64}{i:23}{i:0}{i:10}{s:0.0}{i:2}{i:1}{s:m}{i:-1}{i:-1}{i:0}{i:557}{b:false}`

@XePeleato

**Comment by Speaqer** [comment]
`RoomUser`s packet follows `HEntity` structure. [HEntity.parse](https://github.com/sirjonasxx/G-Earth/blob/master/G-Earth/src/main/java/gearth/extensions/parsers/HEntity.java#L67) iterates whole packet and returns `HEntity[]`. 

`RoomUserTalk`s first integer is user's index in the room. After you've parsed `RoomUser` packet and stored the `HEntity` array, you can lookup the matching entity by the index.

**Comment by sep1** [comment]
Thanks!
```
HPacket packet = message.getPacket();
HEntity[] roomUsersList = HEntity.parse(packet);
```
