### ISSUE TITLE
I stay at 76% and never enter the hotel. / Se me queda en 76% y nunca entra en el hotel.

### ISSUE THREAD

**Issue by alvarovallinas** [sirjonasxx/G-Earth#37]
**Español:**
Hola, Buenas. Les escribo porque no consigo entrar. He instalado java, c ++ redistributable 2017, he probado a reiniciar, ejecutar el porgrama en administrador, he instalado el paquete correspondiente a mi PC (64 bits), he probado en Opera, etc... Pero haga lo que haga nunca termina de cargar. No soy para nada un usuario avanzado, es más, sé lo más básico. Pero agradecería una ayuda, ya que han parcheado Tanji me gustaría darle una oportunidad a este. Un saludo, y espero una respuesta, gracias.

----> [https://i.imgur.com/6xzFrVs.png](PHOTO)

**English:**
Hello. I write to you because I can not get in. I have installed java, c ++ redistributable 2017, I have tried to restart, run the program in administrator, I have installed the corresponding package to my PC (64 bits), I have tried Opera, etc ... But whatever I do never ends to load. I'm not an advanced user at all, it's more, I know the basics. But I would appreciate a help, since they have patched Tanji I would like to give this one a chance. Greetings, and I hope an answer, thank you.

**Comment by capacitor0** [comment]
Try running G-Earth with cmd.exe as admin

**Comment by sirjonasxx** [comment]
Try a different browser if you are sure you have the right c++ redistributable
