### ISSUE TITLE
Add a scheduler item from my extension

### ISSUE THREAD

**Issue by sep1** [sirjonasxx/G-Earth#38]
Hello, how can i add a scheduler item from my extension?

I would like to do something like that:

```
    public void onButtonClicked(){
    	ScheduleItem newItem = new ScheduleItem(
                scheduleItemList.size(),
                false,
                new Interval(myExtensionInterval),
                new HPacket(myExtensionPacket),
                myExtensionSideDestination;

        addItem(newItem);
    }
```

**Comment by XePeleato** [comment]
Next time better explain it with words, since we don't know what a ScheduleItem is or why there's a 'false' passed as the second parameter.

Now about your question, something like this would probably work:
```
boolean enabled = false;
public void onClickToggleScheduler() {
    enabled = !enabled;
}

public void initExtension() {
    new Thread(() -> whatever()).start();
}

public void whatever() {
    while (enabled) {
        Thread.sleep(interval);
        sendPacket(whatever);
    }
}
```

**Comment by sep1** [comment]
I meant ScheduleItem from package gearth.ui.scheduler.
Thanks for your answer!

**Comment by XePeleato** [comment]
Oh I see, sorry for the misunderstanding, that class is meant to be used with G-Earth's scheduler.

If you want to schedule packets from your extension you'll have to code your own scheduler class since there's no way to use G-Earth's scheduler directly from your extension.

**Comment by sirjonasxx** [comment]
As of now in development branch, he underlying code for Scheduler has been exposed so now you can call "new Scheduler<ScheduleItem>()" and ".add(scheduleItem)" etc within a java extension

However, this will not add anything to the G-Earth Scheduler UI, since this uses its own instance of Scheduler
