### ISSUE TITLE
It connects, but is virtually invalid

### ISSUE THREAD

**Issue by brasileiro543** [sirjonasxx/G-Earth#40]
in the package logger, there is no longer what happens in the rooms, just letters, and as if you had connected and at the same time did not, the extensions do not work.

**Comment by XePeleato** [comment]
A screenshot showing the problem would definitely help.

**Comment by brasileiro543** [comment]
At the moment, I can not and I have no impressions about the problem, but I can say, what harbieAPI stays out of, and is different from normal, it is to stay connected but no, it gets false

**Comment by emersondeso** [comment]
I have the same problem
