### ISSUE TITLE
Click on yes and then the .exe disappears

### ISSUE THREAD

**Issue by Bruxes** [sirjonasxx/G-Earth#41]
[https://i.imgur.com/FgSLDho.png](url) Every time this message appears and I click on yes the .exe just closes.

**Comment by KingR187** [comment]
i have the same problem. can some1 help?

**Comment by XePeleato** [comment]
Harble's API is down, it will hopefully be back soon. I'll close the issue whenever that happens, please have a bit of patience :-)

**Comment by KingR187** [comment]
Oh ok thank you. So tanji have the same problem, right?

**Comment by XePeleato** [comment]
No it doesn't

**Comment by sirjonasxx** [comment]
this issue is probably not related to G-Earth but to your extension, reopen issue if not the case
