### ISSUE TITLE
HableAPI

### ISSUE THREAD

**Issue by mamama12** [sirjonasxx/G-Earth#42]
Does anyone know what this HableAPI is, and what it means? I just know it's disabled. something that is not normal. is causing any application to not [work,](url) the extension also does not work. because of him. Does anyone help me activate?
![image](https://user-images.githubusercontent.com/50047556/56849457-e4092d80-68ca-11e9-9e66-5d8f0dec9e6a.png)

**Comment by emersondeso** [comment]
I have the same problem
