### ISSUE TITLE
How this program decrypt the packets from Habbo?

### ISSUE THREAD

**Issue by gabrielpacheco23** [sirjonasxx/G-Earth#44]
I'm not good with Java but I would like to know how this program decrypt the packets coming from Habbo server, especially on Linux. I've read the code files in 'mem' folder but I couldn't understand it well.

**Comment by XePeleato** [comment]
Hi, the code locates the flash process and then reads its memory, searching for the RC4 table, where the key is derived from. That key is enough to decrypt the packets.

**Comment by VitorGPereira97** [comment]
I can call Gmem with python code(Python software to get/read the flash memory)?

**Comment by dosier** [comment]
> Can i call Gmem with python code(Python software to get/read the flash memory)?

Yes, [G-Mem](https://github.com/sirjonasxx/G-Mem) is a program written in C++. U can either compile it urself, or use the one shipped with G-Earth. Just run the executable as a process from python and read the input stream, here's how it is done in G-Earth for windows: https://github.com/sirjonasxx/G-Earth/blob/master/G-Earth/src/main/java/gearth/protocol/memory/habboclient/windows/WindowsHabboClient.java
