### ISSUE TITLE
Unknown load command 9

### ISSUE THREAD

**Issue by Macemas** [sirjonasxx/G-Earth#45]
I've done a bit of researching and it appears to be related to the version of OSX I'm running. When attempting to sign G-Mem I get the error "malformed object (unknown load command 9) which somewhere google said it's because I'm running too old of a version of OSX (10.11.6)

Is there anyway to circumvent this?

**Comment by sirjonasxx** [comment]
Our userbase for mac is very small so chances are low we can help you here. Feel free to let us know if you found a fix, will add to the troubleshooting page
