### ISSUE TITLE
Not work in Habbo Retroservers

### ISSUE THREAD

**Issue by Prodbydie** [sirjonasxx/G-Earth#46]
I connect to the retroserver when the program is looking for the retroserver, but it can't find it. bssitalia.eu

**Comment by XePeleato** [comment]
Support for retroservers is very limited. I guess you have not read the wiki, but without any other details there's little we can do.

**Comment by XePeleato** [comment]
It's a known limitation so I'm going to close it, better use Tanji for retros.

**Comment by Prodbydie** [comment]
tanji don't work.

**Comment by XePeleato** [comment]
It does, I actually got into that retro yesterday with Tanji, it needs some configuration but this is not the place to discuss about that.
