### ISSUE TITLE
g-earth dont open

### ISSUE THREAD

**Issue by alberto64674yt** [sirjonasxx/G-Earth#47]
y click the .exe as admin but never start/appear g-earth and y have the requirements java, visual studio with redistributables the java jre etc.... but never start g-earth

**Comment by XePeleato** [comment]
Can you confirm that it's Java 8? Open a command prompt and type `java -version` it should be 1.8.0 (java 8). If you have multiple versions of java and know their location you can do `C:\Java8_Location\bin\java.exe -jar whatever\G-Earth....\G-Earth.jar` to load the jar directly from an **elevated** command prompt (with admin permissions)

**Comment by alberto64674yt** [comment]
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
i have y think all correct but never open when execute the .exe or the jar file y try the 2

**Comment by sirjonasxx** [comment]
There are known issues with the .exe launcher, it does not work for a few people. For now you should be good to go with the command line

**Comment by sirjonasxx** [comment]
should be fixed next release
