### ISSUE TITLE
Missing Packet Name and Hash

### ISSUE THREAD

**Issue by Pandafuchs** [sirjonasxx/G-Earth#48]
Here is an example of a missing Name and Hash for a Packet:

Incoming[430] <- [0][0][0][137][1]®[1][1][129]Zg[0][9]Dachboden[0][23]Äç[0][9]Dominik-N[0][0][0][0][0][0][0][0][0][0][0]2[0][29]Was mag sich hier verstecken?[0][0][0][1][0][0][0]b[0][0][0][0][0][0][0][12][0][0][0][0][0][0][0]([0][0][0][0][0][0][0][0][0][0][0][0][0][0][0][0][1][0][0][0][1][0][0][0][1][0][0][0][1][0][0][0][14][0][0][0][2]

The Intercept Method only accepts Hashes or Names, how do I get the Name or Hash from this Paket, or how do I intercept it by the Header-ID?

**Comment by XePeleato** [comment]
If you know the real name of the message, just say it so that I can add it. Otherwise, you can use the intercept from ExtensionForm instead of the one from HashSupport

**Comment by Pandafuchs** [comment]
I don't know where to get that name from, but that intercept of the Extension works like a charm, didn't know that exists - thanks a lot!
