### ISSUE TITLE
Fail to build

### ISSUE THREAD

**Issue by Alynva** [sirjonasxx/G-Earth#51]
I'm trying to create some extensions but when I try to build the repo as is, I get this error:

> The build could not read 3 projects -> [Help 1]
> 
>   
>   The project G-Earth:AdminOnConnect:0.0.1-beta (/home/osboxes/Downloads/G-Earth-master/Extensions/AdminOnConnect/pom.xml) has 1 error
>     Non-resolvable parent POM: Could not transfer artifact G-Earth:G-Earth-Parent:pom:1.0 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/G-Earth/G-Earth-Parent/1.0/G-Earth-Parent-1.0.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. and 'parent.relativePath' points at wrong local POM @ line 13, column 13 -> [Help 2]+
>   
>   The project G-Earth:BlockReplacePackets:0.0.1-beta (/home/osboxes/Downloads/G-Earth-master/Extensions/BlockReplacePackets/pom.xml) has 1 error
>     Non-resolvable parent POM: Failure to transfer G-Earth:G-Earth-Parent:pom:1.0 from http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact G-Earth:G-Earth-Parent:pom:1.0 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/G-Earth/G-Earth-Parent/1.0/G-Earth-Parent-1.0.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. and 'parent.relativePath' points at wrong local POM @ line 13, column 13 -> [Help 2]
>   
>   The project G-Earth:HappySpeech:0.0.1-beta (/home/osboxes/Downloads/G-Earth-master/Extensions/HappySpeech/pom.xml) has 1 error
>     Non-resolvable parent POM: Failure to transfer G-Earth:G-Earth-Parent:pom:1.0 from http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact G-Earth:G-Earth-Parent:pom:1.0 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/G-Earth/G-Earth-Parent/1.0/G-Earth-Parent-1.0.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. and 'parent.relativePath' points at wrong local POM @ line 13, column 13 -> [Help 2]
> 
> To see the full stack trace of the errors, re-run Maven with the -e switch.
> Re-run Maven using the -X switch to enable full debug logging.

Java 8. NetBeans 8.2 and Ubuntu 19.10

**Comment by XePeleato** [comment]
HI, please apply commit 01bde4f2b2d92c264158bf3a5bb7235a1c8b5f84 to every extension and see if it still happens. The issue here is that the extensions are being built before G-Earth is, so the extensions look for G-Earth in maven's cache. Instead, we want them to use the relative path to find it.

**Comment by sirjonasxx** [comment]
@Alynva could you confirm if the solution worked for you?

**Comment by Alynva** [comment]
Not really, I was using the 6064f8f8845c4b8c2b6b53a79d5ecae744168fcf commit, so this change was already there. But in some way my friend made it work. I had to change from NetBeans to Eclipse too.
