### ISSUE TITLE
Fehler: Main class gearth.Main could not be found or loaded

### ISSUE THREAD

**Issue by gurkentier** [sirjonasxx/G-Earth#53]
I get an error message trying to run G-Earth v1.0 on:
5.5.16-1-MANJARO #1 x86_64 GNU/Linux

I downloaded the archive from the releases section and tried to run:

sudo java -jar G-Earth.jar

Result:
Fehler: Hauptklasse gearth.Main konnte nicht gefunden oder geladen werden
(Error: Main class gearth.Main could not be found or loaded)

When I unzip the jar archive I can clearly find the gearth directory and the .class file in it.
Even my tab-completion shows me gearth.Main when using
sudo java -cp G-Earth.jar gearth.Main

As well using absolute paths did not work for me.

**Comment by sirjonasxx** [comment]
Have you tried this solution 
![image](https://user-images.githubusercontent.com/36828922/80659224-9ba9c000-8a88-11ea-9540-92cccb522184.png)

**Comment by gurkentier** [comment]
Sorry dude I did only skim through the troubleshooting guide ^^

**Comment by gurkentier** [comment]
I am trying the same thing on macOS now. I have javaFX installed, but its still not working.
<img width="994" alt="Bildschirmfoto 2020-07-25 um 13 32 23" src="https://user-images.githubusercontent.com/46462486/88456163-c33bd900-ce7b-11ea-852e-7428e5468d7b.png">

**Comment by sirjonasxx** [comment]
please dont open 2 issues

**Comment by gurkentier** [comment]
These are 2 different issues
