### ISSUE TITLE
G-Earth just says "Waiting For Connection", but nothing happens.

### ISSUE THREAD

**Issue by Dtonadorr** [sirjonasxx/G-Earth#54]
Whenever I try to use G-Earth, I get the message that was announced in the title of this topic. I've tried countless things taught in other topics, but it doesn't work. My java is up to date, and so is my NET Framework. 

 Windows 10, 64 bits.

If any information is missing, forgiveness. Help me, I've been trying to connect for days.

![Habbo error](https://user-images.githubusercontent.com/65180051/81581096-a4ea3500-9384-11ea-8446-dd427606a62f.png)

**Comment by sirjonasxx** [comment]
Hi, what was the issue/solution here?
