### ISSUE TITLE
Just ''Waiting For Connection"

### ISSUE THREAD

**Issue by Dtonadorr** [sirjonasxx/G-Earth#55]
Whenever I try to use G-Earth, I get the message that was announced in the title of this topic. I've tried countless things taught in other topics, but it doesn't work. My java is up to date, and so is my NET Framework. 

 Windows 10, 64 bits.

If any information is missing, forgiveness. Help me, I've been trying to connect for days.

![Habbo error](https://user-images.githubusercontent.com/65180051/81581264-e11d9580-9384-11ea-9e66-f685f5da5986.png)

**Comment by LilithRainbows** [comment]
Try to disable Opera VPN.

**Comment by LilithRainbows** [comment]
Try to disable Opera VPN or any other active VPN software/extension.

**Comment by Dtonadorr** [comment]
Opera VPN was already disabled. As a precaution, I will remove the extension. Do you have any other tips or ideas about why you're not connecting?

**Comment by LilithRainbows** [comment]
> Opera VPN was already disabled. As a precaution, I will remove the extension. Do you have any other tips or ideas about why you're not connecting?

Try running G-Earth.exe as Admin, also you can try another browser or the latest development build.
Here you can download a compiled version: https://github.com/LilithRainbows/G-Earth/releases

**Comment by Dtonadorr** [comment]
First of all, thank you for trying to help me. I always run G-Earth as ADM, and I also downloaded 2 more browsers and still have the same situation. Nothing has been resolved.

**Comment by LilithRainbows** [comment]
> First of all, thank you for trying to help me. I always run G-Earth as ADM, and I also downloaded 2 more browsers and still have the same situation. Nothing has been resolved.

Weird, maybe your antivirus is blocking something 🤔

**Comment by Dtonadorr** [comment]
I do not have antivirus

**Comment by LilithRainbows** [comment]
> I do not have antivirus

I don't know what else it could be. 😭

**Comment by sirjonasxx** [comment]
https://github.com/sirjonasxx/G-Earth/wiki/Troubleshooting have you read through the troubleshooting page? Your issue is categorized under problem 3 over there. If you did please follow the instructions on that wiki page on creating an issue

**Comment by TheRevenge** [comment]
I think that GEarth is unable to modify your host file. It can be caused by an antivirus (even windows defender) so you better check twice

**Comment by sirjonasxx** [comment]
@Dtonadorr are you still having the same issue?

**Comment by Dtonadorr** [comment]
Gentlemen, I managed to solve the problem by formatting the PC and installing all the drivers again. I am very grateful for the wonderful support you have offered me.

**Comment by sirjonasxx** [comment]
Good to hear!
