### ISSUE TITLE
Missing HarbleAPI Hash

### ISSUE THREAD

**Issue by LilithRainbows** [sirjonasxx/G-Earth#57]
@XePeleato 
Can you add the Outgoing Hash "RequestUserProfile" ?

Example:
```
Outgoing[602] -> [0][0][0][7][2]Z[0][0][0][1][1]
{l}{u:602}{i:1}{b:true}
--------------------
[UserProfile]
Incoming[1260] <- [0][0][0]h[4]ì[0][0][0][1][0][4]aapo[0]1hr-165-45.hd-208-14.ch-250-64.lg-285-82.sh-290-64[0][7]huuhaa![0][10]25-07-2003[0][0][1]^[0][0][0][14][0][0][0][0][0][0][0][28]ÀÛ[0][1]
{l}{u:1260}{i:1}{s:"aapo"}{s:"hr-165-45.hd-208-14.ch-250-64.lg-285-82.sh-290-64"}{s:"huuhaa!"}{s:"25-07-2003"}{i:350}{i:14}{i:0}{s:""}{i:1884379}{b:false}{b:true}
```

Thanks.

**Comment by LilithRainbows** [comment]
Also the Incoming Hash "AddUserBadge" is missing.

Example:
```
Incoming[3408] <- [0][0][0][19][13]P[2]`¬d[0][0][0][1][0][0][0][1][0][3]ADM
{l}{u:3408}{i:39890020}{i:1}{i:1}{s:"ADM"}
```

**Comment by BurakDev** [comment]
@XePeleato Add all hashes, even if you don't have the name of the packet 🤓

**Comment by XePeleato** [comment]
Both added. I'll consider adding every packet to the API, if there's any other missing hash let me know before closing the issue.

Thanks!

**Comment by sirjonasxx** [comment]
Outgoing[3705] -> [0][0][0][6][14]y[0]"[150][157]
{l}{u:3705}{i:2266781}

this one is for composting a monsterplant

**Comment by XePeleato** [comment]
CompostMonsterplant updated

**Comment by LilithRainbows** [comment]
> Both added. I'll consider adding every packet to the API, if there's any other missing hash let me know before closing the issue.
> 
> Thanks!

Thanks 💖
Another one is the user permissions packet, to enable HC commands, furni ID viewer, etc.
However i'm not sure what is the Header name, maybe UserPermissions?
```
Incoming[2567] <- [0][0][0][11][10][7][0][0][0][0][0][0][0][0][0]
{l}{u:2567}{i:0}{i:0}{b:false}
```

**Comment by XePeleato** [comment]
Right, UserPermissions. It has been updated as well 😊

**Comment by LilithRainbows** [comment]
> Right, UserPermissions. It has been updated as well 😊

Thanks.
I have more xDD

**UserClothes**
```
Incoming[934] <- [0][0][1][14][3]¦[0][0][0][11][0][0][13]v[0][0][13]½[0][0][13]¾[0][0][13]L[0][0][13]#[0][0][13]ç[0][0][14]â[0][0][14]ý[0][0][14]þ[0][0][14]o[0][0][13][141][0][0][0][11][0][19]clothing_cladydress[0][19]clothing_polkadress[0][19]clothing_polkadress[0][18]clothing_knitalien[0][15]clothing_party2[0][13]clothing_love[0][19]clothing_grandetail[0][22]clothing_croppedjumper[0][22]clothing_croppedjumper[0][13]clothing_tutu[0][15]clothing_ribbon
{l}{u:934}{i:11}{i:3446}{i:3517}{i:3518}{i:3404}{i:3363}{i:3559}{i:3810}{i:3837}{i:3838}{i:3695}{i:3469}{i:11}{s:"clothing_cladydress"}{s:"clothing_polkadress"}{s:"clothing_polkadress"}{s:"clothing_knitalien"}{s:"clothing_party2"}{s:"clothing_love"}{s:"clothing_grandetail"}{s:"clothing_croppedjumper"}{s:"clothing_croppedjumper"}{s:"clothing_tutu"}{s:"clothing_ribbon"}
```

**RoomUserData** (I'm not 100% sure about the Header name)
```
Incoming[1798] <- [0][0][0]n[7][6][0][0][0][3][0][93]hr-515-45.hd-600-10.ch-665-71.lg-3781-73-71.ha-3614-91-71.he-3469-73.fa-3276-72.ca-3702-71-71[0][1]f[0][0][0][0][23]à
{l}{u:1798}{i:3}{s:"hr-515-45.hd-600-10.ch-665-71.lg-3781-73-71.ha-3614-91-71.he-3469-73.fa-3276-72.ca-3702-71-71"}{s:"f"}{s:""}{i:6112}
```

**Comment by sirjonasxx** [comment]
Not sure what the name of this is, but this is a useful one for getting the room id

Incoming[310] <- [0][0][0][15][1]6[0][7]model_j[1] [157]½
{l}{u:310}{s:"model_j"}{i:27303357}

**Comment by LilithRainbows** [comment]
> Not sure what the name of this is, but this is a useful one for getting the room id
> 
> Incoming[310] <- [0][0][0][15][1]6[0][7]model_j[1] [157]½
> {l}{u:310}{s:"model_j"}{i:27303357}

**RoomModel** (i think).

**Comment by sirjonasxx** [comment]
Incoming[374] <- [0][0][0]$[1]v[0][0][0][28][0][12]g-earth gang[0][0][0][0][0][0][0][3][0][0][0][0][0][0][0][2]
{l}{u:374}{i:28}{s:"g-earth gang"}{i:0}{i:3}{i:0}{i:2}

For chats in the room

**Comment by XePeleato** [comment]
Sorry for the delay, I believe it's all fixed, but should you find any other outdated hashes let me know.

I've also added your names to harble.net (not the most visited page, I know) as a sign of gratitude, you can think of it as a hall of fame. Thanks! 🍸

**Comment by LilithRainbows** [comment]
Aww, thanks, so cute. 💖🌈
Great job!

**Comment by LilithRainbows** [comment]
```
Incoming:
{l}{u:2664}{s:"furni_placement_error"}{i:1}{s:"message"}{s:"${room.error.cant_set_not_owner}"}
```
Maybe **CustomNotification**

**Comment by Pandafuchs** [comment]
{l}{u:2007}{i:1}{s:"am gorl i cannot ask you to do anything |w|"}{i:0}{i:0}{i:0}{i:-1}

This is RoomUserTalk

@XePeleato Can you explain how to add these Hashes to the cache file? So we can do it ourselves if you don't have the time to add these things yourself.

**Comment by sirjonasxx** [comment]
![image](https://user-images.githubusercontent.com/36828922/91709839-9ddd7180-eb83-11ea-8114-813ee47dde50.png)

MarketplaceOffers and its response or something

**Comment by sirjonasxx** [comment]
![image](https://user-images.githubusercontent.com/36828922/91717865-9a051b80-eb92-11ea-86a5-1c4757b7f1f0.png)
outgoing packet for collecting coins (button) from marketplace

**Comment by sirjonasxx** [comment]
rip flash :(
