### ISSUE TITLE
Pre-compiled Repo For Linux? (Ubuntu LTS 20.04)

### ISSUE THREAD

**Issue by evanti11** [sirjonasxx/G-Earth#58]
Is there a pre-compiled version of this? I'm completely clueless when it comes to Java, and have no clue how to compile this in the directory obtained from git cloning this repo. Executing the command given for linux users outputs: `Error: Unable to access jarfile G-Earth.jar` presumably because I haven't compiled it and the .jar doesn't exist.

Have no clue where to go from here, and instructions on compiling haven't been very helpful for this specific situation.

**Comment by sirjonasxx** [comment]
https://github.com/sirjonasxx/G-Earth/releases

**Comment by evanti11** [comment]
So download the .jar and execute it from any directory, or is there some sort of directory I should be putting it in before executing the command? Thanks for your eerily quick reply.

**Comment by sirjonasxx** [comment]
It should be fine if you extract the contents of G-Earth.rar into a new folder, location shouldnt matter

**Comment by evanti11** [comment]
Oh so download the .rar specifically for linux in the releases link you gave as opposed to git cloning like I did?

**Comment by sirjonasxx** [comment]
Yes, that is the compiled version

**Comment by evanti11** [comment]
Oh wow, I'm an idiot, cheers friend, sorry for wasting an issue thread on this.
