### ISSUE TITLE
Error: Could not find or load main class gearth.Main

### ISSUE THREAD

**Issue by evanti11** [sirjonasxx/G-Earth#59]
So, I've installed javafx, set java 8 to default, and also tried using SDKMan to revert to java 8 as a default before running and am still getting this error 
`Error: Could not find or load main class gearth.Main` 
when I try to execute 
`sudo java -jar G-Earth.jar` 

Ubuntu LTS 20.04

**Comment by the1scient** [comment]
Well, i can't actually find the G-Earth.jar linux file. Where it is stored?

**Comment by sirjonasxx** [comment]
> Well, i can't actually find the G-Earth.jar linux file. Where it is stored?

https://github.com/sirjonasxx/G-Earth/releases/tag/1.1
It is in G-Earth-1.1_linux.rar

**Comment by the1scient** [comment]
> https://github.com/sirjonasxx/G-Earth/releases/tag/1.1
> It is in G-Earth-1.1_linux.rar

Thank you very much! Now I have kinda' the same error @evanti11 has.
`Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application` when i execute `sudo java -jar G-Earth.jar`.

**Comment by sirjonasxx** [comment]
@evanti11 were you able to solve this issue by any chance?

**Comment by miguegame621-design** [comment]
I get the same thing but for Windows
