### ISSUE TITLE
MarketplaceQuery not being decoded correctly

### ISSUE THREAD

**Issue by Hackditano** [sirjonasxx/G-Earth#64]
I was looking for a furni, Glass Bottle 8 / Botella de cristal 8 (i'm from habbo.es) and I noticed that the resulting expression from decoding the packet looks weird.

This is the packet:
Incoming[3055] <- [0][0][0]0[11]ï[0][0][0][1][3]Þô[1][0][0][0][1][0][0][0][1][0][0][19]*[0][0][0][0][0][0][0][0][0][9][0][0][8][159][0][0][0][9][0][0][0][1][0][0][0][1]

And its structure:
{l}{u:3055}{s:""}{b:false}{i:17030900}{b:true}{i:1}{i:1}{i:4906}{i:0}{s:""}{i:9}{i:2207}{i:9}{i:1}{i:1}

But I think the correct expression is this one:
{i:3055}**{i:1}{i:64943105}**{i:1}{i:1}{i:4906}{i:0}{s:""}{i:9}{i:2207}{i:9}{i:1}{i:1}

**Comment by sirjonasxx** [comment]
good find, its a prediction algorithm but it could definitely be improved for this case. Let me know if you find any others

**Comment by Hackditano** [comment]
thanks sir, I will

**Comment by sirjonasxx** [comment]
predictor seems to work fine for the packet if the furni ID doesnt end in [0] or [1]

**Comment by sirjonasxx** [comment]
will need to see if fix is possible without fucking other packets 🤔

**Comment by gurkentier** [comment]
can confirm this issue

**Comment by sirjonasxx** [comment]
closing packet prediction issues for now
