### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by HeroinGyrl** [sirjonasxx/G-Earth#66]
Hey!

I have some suggestions that could be very useful.

1. A filter where you enter the header and it then no longer appears in the logger.
2. Leave the window where the packets are displayed open and simply clear the window when connecting again
   - this is good if you were banned from a retro and you want to see the packets. because for now the window closes automatically

I would be very happy greetings.

**Comment by sirjonasxx** [comment]
> Leave the window where the packets are displayed open and simply clear the window when connecting again
this is good if you were banned from a retro and you want to see the packets. because for now the window closes automatically

Just a heads up, you can already use the `-t` commandline flag to packetlog inside your terminal instead of in a new window

**Comment by sirjonasxx** [comment]
the second feature is available in 1.4.1, won't implement the first one, since the spam filter can filter out annoying packets already
