### ISSUE TITLE
G-Earth has experienced an issue

### ISSUE THREAD

**Issue by gurkentier** [sirjonasxx/G-Earth#67]
After struggling with JavaFX, I managed to get it working. I installed java 1.8 which came bundled with JavaFX already. Now I am encountering the following issue:
When I connect to the Hotel, a popup appears mentioning that "G-Earth has experienced an issue", redirecting me to the Troubleshooting guide. None of the cases was applying for me. No Exception or Stack Trace unfortunately so I can see it.

**Comment by gurkentier** [comment]
<img width="822" alt="Bildschirmfoto 2020-08-04 um 13 15 05" src="https://user-images.githubusercontent.com/46462486/89287941-1e788300-d655-11ea-8c58-784f75f6a329.png">

**Comment by sirjonasxx** [comment]
Is this on mac?

**Comment by gurkentier** [comment]
Yes it is

**Comment by XePeleato** [comment]
Is SIP (System Integrity Protection) enabled? If so, you have to disable it, or at least, the task_for_pid protection.

**Comment by gurkentier** [comment]
SIP is disabled and task_for_pid protection is also disabled as Im experimenting with task ports at the moment

**Comment by XePeleato** [comment]
Are you using Safari then? If so, please try Firefox or Google chrome.

**Comment by gurkentier** [comment]
I use Chrome

**Comment by gurkentier** [comment]
I solved it - G-Mem hat a bit flipped (exection permission) because of alpha particle emission
