### ISSUE TITLE
RoomData not parsable

### ISSUE THREAD

**Issue by Pandafuchs** [sirjonasxx/G-Earth#68]
``` 
[RoomData]
Incoming[1358] <- [0][0][0]z[5]N[0][1][151]<Ú[0][22]|â[128]¦Greenie Meenieâ[128]¦|[0][146][134]Ö[0][10]CiaoLeben.[0][0][0][0][0][0][0][4][0][0][0]2[0][0][0][0][0][2][0][0][0]m[0][0][0][0][0][0][0][12][0][0][0][0][0][0][0]8[1][0][0][0][0][0][0][1][0][0][0][1][0][0][0][1][1][0][0][0][0][0][0][0][0][0][0][0][1][0][0][0][14][0][0][0][2]
{l}{u:1358}{b:false}{i:26688730}{i:1473762}{i:-2136586382}{i:1701146217}{i:1696615781}{i:1701734757}{i:-494885252}{i:9602774}{s:"CiaoLeben."}{i:0}{i:4}{i:50}{s:""}{i:2}{i:109}{i:0}{i:12}{i:0}{i:56}{b:true}{i:0}{s:""}{b:true}{i:1}{i:1}{b:true}{i:0}{i:0}{i:1}{i:14}{i:2}
```

This is a RoomData Packet. As you can see in the Byte-Display there is a String "Greenie Meenie" but its not represented in the String-Form. All the {-Brackets are integers apart from two empty ones in between. 

If I try to parse it with Harble I get: 

```
Connection failed; is G-Earth active?
java.lang.ArrayIndexOutOfBoundsException: 126
	at gearth.protocol.HPacket.readByte(HPacket.java:106)
	at gearth.protocol.HPacket.readString(HPacket.java:197)
	at gearth.protocol.HPacket.readString(HPacket.java:192)
	at gearth.protocol.HPacket.readString(HPacket.java:184)
	at extensions.chatarchiver.ChatArchiver.onRoomData(ChatArchiver.java:56)
	at gearth.extensions.extra.harble.HashSupport.lambda$2(HashSupport.java:72)
	at gearth.extensions.Extension.run(Extension.java:198)
	at extensions.chatarchiver.ChatArchiver.main(ChatArchiver.java:24)
```

this is my code:

```
    	HPacket packet = hMessage.getPacket();
    	packet.readBoolean();
    	packet.readInteger();
    	packet.readInteger();

    	String msg = packet.readString();
```

edit: might be related to: #64

**Comment by gurkentier** [comment]
Same issue here

**Comment by sirjonasxx** [comment]
[0][0][0]z
[5]N
[0]
[1][151]<Ú
[0][22]|â[128]¦Greenie Meenieâ[128]¦
|[0][146][134]Ö
[0][10]CiaoLeben.
[0][0][0][0]
[0][0][0][4]
.....

The structure starts with {b}{i}{s} and not {b}{i}{i}{s}. important to note that you can't use g-earth predictions as fact, its hard to predict a string that contains special characters

I already have an improvement for #64 in mind that would apply to this issue as well, so I'll leave this open until it's implemented

**Comment by sirjonasxx** [comment]
> If I try to parse it with Harble I get:

just for clarity, the structure of this packet wasnt given by harble api. If it was, it wouldve been correct

**Comment by Pandafuchs** [comment]
Okay I gotcha. The String I extract looks like this now:

`|â?¦Greenie Meenieâ?¦|`

The actual room name is:

`♥... Greenie Meanie...♥`

With the hearts obviously not being emojis but the |-Heart from Habbo Alt codes. I understand its hard to predict strings esepcially when they have special chars, maybe you'll find a genius solution to still predict it. I was just confused that I saw the string in the Packet Logger Window but not anymore in the "predicted" format in bracket-format display.

**Comment by sirjonasxx** [comment]
I will be looking into improving string prediction and will also implement a system for recognizing patterns within packets, so earlier received RoomData packets will contribute in predicting structures of new packets

**Comment by sirjonasxx** [comment]
closing packet prediction issues for now
