### ISSUE TITLE
give me the BOT program please

### ISSUE THREAD

**Issue by pickausernamewhut** [sirjonasxx/G-Earth#70]
thanks :(

**Comment by pickausernamewhut** [comment]
**dont close this what the f**********************************************uck´????**

**Comment by sirjonasxx** [comment]
How is your issue related to G-Earth

**Comment by pickausernamewhut** [comment]
because *I LOVE* g-earth so much and I need it ʕ•ᴥ•ʔ  ༼ಢ_ಢ༽

**Comment by sirjonasxx** [comment]
I love g-earth and I need money, should I create an issue to ask for money?

**Comment by sirjonasxx** [comment]
BOT tools have nothing to do with g-earth, and is not something I would support as well. So im afraid I cant help

**Comment by pickausernamewhut** [comment]
Yea why not? You're the owner of G-Earth - **DO IT**!
 

- [ ] do a paypal donation button

**Comment by sirjonasxx** [comment]
I love g-earth and i want to be president of the united states, should I make an issue for it

**Comment by pickausernamewhut** [comment]
OF COURSE!!! **FUCK DONALD TRUMP**  凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸  _fuckhispussy_  凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸   凸-_-凸
