### ISSUE TITLE
Loading Blocks at 76%

### ISSUE THREAD

**Issue by rhain1000** [sirjonasxx/G-Earth#73]
> The loading blocks always at 76% even with having c++ 2017 
I tested in chrome and firefox and it blocks at 76%

- [ ]

**Comment by sirjonasxx** [comment]
Please follow the guidelines of the troubleshooting page when creating an issue https://github.com/sirjonasxx/G-Earth/wiki/Troubleshooting

![image](https://user-images.githubusercontent.com/36828922/99883282-ca56d600-2c26-11eb-8aea-a2edd487653e.png)
