### ISSUE TITLE
request: would you be able to develop an extension to unlock rooms blocked for breaking the habbo rules

### ISSUE THREAD

**Issue by mandyvandy** [sirjonasxx/G-Earth#74]

**Comment by mandyvandy** [comment]
probably not on the flash but on the unity

**Comment by mandyvandy** [comment]
please add me on discord if you have any questions : Kim Jong- trump#5583

**Comment by sirjonasxx** [comment]
This isn't really the place for extension requests (I doubt this extension is even possible)

Better to ask this in the discord server

**Comment by mandyvandy** [comment]
Hi, maybe not an extension just a way to say it but bypass it, can you give me the discord server, and what discord server is that
