### ISSUE TITLE
java.io.FileNotFoundException: C:\Users\User\Desktop\Windows_64bit\Cache\UNITY-84_ce2766f45c2772a59229f830f2fe2fd5\UnityLoader.js 

### ISSUE THREAD

**Issue by sep1** [sirjonasxx/G-Earth#77]
https://pastebin.com/VxxBRqez

**Comment by sirjonasxx** [comment]
Is this on 1.3.1?

**Comment by sep1** [comment]
Yes. Latest version.

C:\Users\User\Desktop\Windows_64bit>dir /s /b /o:gn
C:\Users\User\Desktop\Windows_64bit\Cache
C:\Users\User\Desktop\Windows_64bit\Extensions
C:\Users\User\Desktop\Windows_64bit\G-Earth.exe
C:\Users\User\Desktop\Windows_64bit\G-Earth.jar
C:\Users\User\Desktop\Windows_64bit\G-Mem.exe
C:\Users\User\Desktop\Windows_64bit\messages.json
C:\Users\User\Desktop\Windows_64bit\Cache\UNITY-84_ce2766f45c2772a59229f830f2fe2fd5
C:\Users\User\Desktop\Windows_64bit\Cache\cache.json
C:\Users\User\Desktop\Windows_64bit\Cache\UNITY-84_ce2766f45c2772a59229f830f2fe2fd5\habbo2020-global-prod.data.unityweb
C:\Users\User\Desktop\Windows_64bit\Cache\UNITY-84_ce2766f45c2772a59229f830f2fe2fd5\habbo2020-global-prod.json
C:\Users\User\Desktop\Windows_64bit\Cache\UNITY-84_ce2766f45c2772a59229f830f2fe2fd5\habbo2020-global-prod.wasm.code.unityweb
C:\Users\User\Desktop\Windows_64bit\Extensions\AdminOnConnect.jar
C:\Users\User\Desktop\Windows_64bit\Extensions\BlockReplacePackets.jar

**Comment by sirjonasxx** [comment]
do you have teamviewer?

**Comment by sep1** [comment]
This issue occurs when you try for the very first time to connect habbo and G Earth and the connection fails for some reason. 
In order to solve this error you need to clear your browser cache and the /Cache folder.
