### ISSUE TITLE
G-earth has experienced an issue

### ISSUE THREAD

**Issue by 1Floopz** [sirjonasxx/G-Earth#80]
![g-e](https://user-images.githubusercontent.com/81023103/111870384-2cb8ac80-8963-11eb-907e-cc1dcf48d40b.png)

i have the java8; jre-8 but already tryed the jdk-8, bouth 64bits like mi pc
mi sistem operacional is an windows 7 64 bits 

im trying connect the g-earth and keep having this problem.

i installed the c++ 2017 too

if someone can help-me, thank you all

**Comment by sirjonasxx** [comment]
Are you on the latest g-earth version?

**Comment by 1Floopz** [comment]
yess i guess so, im on g-earth 1.3.3

**Comment by sirjonasxx** [comment]
Sorry for not getting back to you, have you been able to fix it already? It has most likely have to do with G-Mem.
Are you opening G-Earth with the .exe file? Does it give any errors of missing libraries if you double click G-Mem.exe?

**Comment by sirjonasxx** [comment]
if you still have this issue, make a new issue following the steps described here: https://github.com/sirjonasxx/G-Earth/wiki/Troubleshooting#creating-an-issue
