### ISSUE TITLE
live scripting console not working

### ISSUE THREAD

**Issue by sep1** [sirjonasxx/G-Earth#81]
I'm posting this issue here cause is more related with the G-Python extension.

"Enable G-Python scripting" gives me the following error:
https://imgur.com/MIxJIrg

Note that all the the required packages are installed (qtconsole pyqt5 jupyter-console g-python):
https://imgur.com/TGbLRns

Python version is 3.9.1

**Comment by sirjonasxx** [comment]
i assume this is fixed with my previous comment, otherwise make a new issue
