### ISSUE TITLE
[SUGGESTION] send multiple packets in injection at once

### ISSUE THREAD

**Issue by Edaurd** [sirjonasxx/G-Earth#86]
have maybe something like
{out:Sit}|{out:Stand}
and it will be sent either at the same time if thats possible or with a interval you can specify like this
{out:Sit}|{wait:5}|{out:Stand}
or another way idk you decide bossman

**Comment by sirjonasxx** [comment]
this is already implemented and can be done by putting packets on multiple lines

**Comment by sirjonasxx** [comment]
if you want an interval, use the embedded gpython qtconsole

**Comment by Edaurd** [comment]
how about delays????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????viva brazil????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by sirjonasxx** [comment]
send_to_server("{out:Sit}")
time.sleep(x)
send_to_server("{out:Stand}")

**Comment by tweenkapy** [comment]
wtf
