### ISSUE TITLE
New version is not working in retro habbo with flash

### ISSUE THREAD

**Issue by MiClobiMC** [sirjonasxx/G-Earth#87]
When I put the ip and the retro habbo port it stays intercepting but does not connect something that in previous versions does not happen

**Comment by sirjonasxx** [comment]
details pls

**Comment by MiClobiMC** [comment]
When I try to connect to a retro habbo it stays at 76% and does not load nor does it even open the packetlogger console

**Comment by MiClobiMC** [comment]
Here is the error hlandia habbo retro host 87.98.182.101 port 9223
![errorhlandia](https://user-images.githubusercontent.com/60762569/118414832-d6bb6900-b674-11eb-89e8-985d1421c5cb.JPG)

**Comment by sirjonasxx** [comment]
if you still have this issue, make a new issue following the steps described here: https://github.com/sirjonasxx/G-Earth/wiki/Troubleshooting#creating-an-issue
