### ISSUE TITLE
client stuck at 59% pls help

### ISSUE THREAD

**Issue by iconichabbo** [sirjonasxx/G-Earth#90]
My client (Classic) gets stuck at 59% but the packetlogger shows up. I turned off my VPN and tried using a diff browser but it's not working.

**Comment by iconichabbo** [comment]
screenshots that might help:
https://prnt.sc/19krl3n
https://prnt.sc/19krtli
https://prnt.sc/19ks0p0

**Comment by sirjonasxx** [comment]
if you still have this issue, make a new issue following the steps described here: https://github.com/sirjonasxx/G-Earth/wiki/Troubleshooting#creating-an-issue
